#!/bin/bash
echo "    ________________________________"
echo "   /                                \ "
echo "  (    THIS SCRIPT IS FROM GITHUB    ) "
echo "   \________________________________/ "
echo "      \ "
echo "       \ "
echo "        \.--. "
echo "        |o_o | "
echo "        |:_/ | "
echo "       //   \ \ "
echo "      (_|    |_) "
echo "     / \_   _/ \ "
echo "     \___)=(___/ "
echo "  "