CREATE SEQUENCE USER_SEQUENCE INCREMENT BY 1 START WITH 1;

CREATE TYPE ROLE_TYPE AS ENUM ('ROLE_USER', 'ROLE_ADMIN');

CREATE TABLE USERS
(
    ID       BIGINT PRIMARY KEY NOT NULL DEFAULT NEXTVAL ('USER_SEQUENCE'),
    USERNAME VARCHAR(32)        NOT NULL UNIQUE,
    PASSWORD VARCHAR(255)       NOT NULL,
    EMAIL    VARCHAR(255)       NOT NULL UNIQUE,
    ROLE     VARCHAR(16)        NOT NULL CHECK ( ROLE = 'ROLE_USER' OR ROLE = 'ROLE_ADMIN' ) DEFAULT 'ROLE_USER'
);

CREATE TABLE RAW_USERS
(
    ID           BIGINT PRIMARY KEY NOT NULL DEFAULT NEXTVAL ('USER_SEQUENCE'),
    USERNAME     VARCHAR(32)        NOT NULL,
    PASSWORD     VARCHAR(255)       NOT NULL,
    EMAIL        VARCHAR(255)       NOT NULL,
    CONFIRM_CODE VARCHAR(255)       NOT NULL UNIQUE
);