CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  USERNAME VARCHAR(32) NOT NULL UNIQUE ,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE ,
  ROLE ENUM('ROLE_USER', 'ROLE_ADMIN') NOT NULL DEFAULT 'ROLE_USER');

CREATE TABLE RAW_USERS (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  USERNAME VARCHAR(32) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CONFIRM_CODE VARCHAR(255) NOT NULL UNIQUE);